# Generated by Django 3.1.1 on 2020-10-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201007_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vintage',
            name='average_score',
            field=models.FloatField(default=0),
        ),
    ]
