# Generated by Django 3.1.1 on 2020-10-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_wishlist_vintage'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('vintage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='product.vintage')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
